# Debugging Tacotron 2

In [1]:
import numpy as np
import pandas as pd
from importlib import reload
import os
import torch
from torch.utils.data import DataLoader
from scipy.io import loadmat

In [189]:
import ema
reload(ema)
from ema import train_ema, test_ema

In [319]:
train = train_ema()
train_loader = DataLoader(train, shuffle=True, batch_size = 10)

test = test_ema()
test_loader = DataLoader(test, shuffle=True, batch_size = 10)

In [320]:
gh = iter(train_loader)

hh = iter(test_loader)

In [324]:
(gh.next()[0])

[tensor([12,  5, 16, 19, 12, 23, 28, 12, 40, 15]),
 tensor([19, 34, 23, 26, 19, 10, 37, 19, 26, 14]),
 tensor([40, 42, 26, 22,  6, 31, 23, 33, 16, 16]),
 tensor([26, 26, 37, 23, 17, 33, 34, 35, 38, 38]),
 tensor([41,  9, 33, 19, 42, 19, 30,  4,  4,  4]),
 tensor([38, 33, 18,  8, 26,  8,  5, 19, 19,  9]),
 tensor([15, 19,  8,  6, 37, 21, 23, 38, 12, 33]),
 tensor([ 2,  4, 15, 28, 26, 39, 18,  6, 19,  5]),
 tensor([10, 21,  6, 14, 28, 26, 11, 13,  6, 23]),
 tensor([40, 26, 19, 35, 19, 19, 17,  4, 41, 35]),
 tensor([ 6, 30, 29,  6, 11, 38, 19, 21, 31, 29]),
 tensor([17, 31,  1, 23, 19,  4, 38, 19, 40,  6]),
 tensor([23,  6, 38,  9, 15, 30, 21, 33, 26, 19]),
 tensor([37, 25, 31, 38, 28,  8, 35, 14, 30, 38]),
 tensor([26, 18, 19, 37, 39, 18,  4, 11,  2, 15]),
 tensor([23, 21,  5, 26, 21, 11,  6, 15, 35, 25]),
 tensor([18, 39,  1, 12,  7,  2, 40,  6,  6, 14]),
 tensor([33, 26, 38, 19,  7, 16, 19, 12, 19, 19]),
 tensor([39,  5, 31, 28,  7,  8,  8, 19,  5, 31]),
 tensor([ 2, 26,  4, 39,  7, 33

In [327]:
for i, batch in enumerate(test_loader):
    print(i)

0
1
2
3
4
5
